title: Portfolio
subtitle: B.S. Software Engineering
description: >- # this means to ignore newlines until "baseurl:"
  

url: "https://nwmorrison.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Projects
      url: /blog
    - text: Gallery
      url: /gallery


# Edit Author details (For multi authors check _data/authors.yml)
author_logo: nashProfilePicture.jpg
author: Nash William Morrison
author_bio: Welcome to my software engineering profile. My name is Nash Morrison, 
  a passionate and driven software engineer with a strong foundation built through an ABET-accredited engineering program through Florida Gulf Coast University. 
  This accreditation ensures that my education met rigorous global standards in areas like mathematics, computing, engineering 
  principles, and ethical practices, preparing me to tackle complex challenges and contribute meaningfully to the tech industry.
  Through this profile, I aim to share my work, collaborate with fellow professionals, and continue growing within the ever-evolving 
  world of software development. Thanks for stopping by, I look forward to connecting with you!
author_email: "nwmorrison1086@eagle.fgcu.edu"
author_location: Fort Myers, Florida
typewrite-text: Welcome to my Software Engineering Portfolio.
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Connors Steak & Seafood
              company_logo: logo_connors.png
              company_url: https://www.connorsrestaurant.com/fort-myers-fl-steakhouse.html
              designation: Waiter
              description: Fine Dining
              visibility: true
            - company_name: P.F. Chang's
              company_logo: pfchangs_logo.tmb-0.png
              company_url: https://www.pfchangs.com/
              designation: Waiter
              description: Fast-Paced Environment
              visibility: true

# Education
author_education_details:
              - college_logo: fgcu_logo.png
                college_name: Florida Gulf Coast University
                college_url: https://www.fgcu.edu/
                college_degree: Software Engineering
                description: Bachelor of Science
                college_gpa: GPA [3.80]
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: tetris.jpg
                project_title: -Py-tris-
                project_description: Built Tetris using Python
                project_url: https://nwmorrison.github.io/projects/PyTris/
                visibility: true
              - project_thumbnail: mctesters.png
                project_title: McDonald's Automation Testing
                project_description: Group Project Utilizing Maven Repository
                project_url: https://nwmorrison.github.io/projects/McTesters/
                visibility: true

# social links
# twitter_username:
linkedin_username: nashwmorrison
github_username:  NWMorrison
youtube_username: NashWMorrison
# instagram_username:
# facebook_username:
# telegram_username:

# wakatime username (coding activity)
wakatime_username: NWMorrison


# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"


collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
